### ISSUE TITLE
Motion Tablet scanner bug

### ISSUE THREAD

**Issue by c-riess** [DataSplice/uniwedge-2000-windows#46]
DataSplice 5.1.141
Motion Tablet F5TE
Uniwedge Dev Branch
Intermec WedgeLite 1.0.1.2 (ISDC_RS:2.5.9.0) , (ED30/EA11 BF3_220_)

**Issue:**  Additional noise being inserted into 'DS_SCANNER_INPUT' attribute when a long scan(greater than 1s) occurs, however, short scans(instant) result in a successful fetch.

We ultimately proved Uniwedge to be the main culprit when only alphanumeric characters were accepted and regardless of the scan time there was as successful fetch.

> Changing _**${MX_LOOKUP_SCANNED_ITEM}**_ from _**${DS_SCANNER_INPUT}**_ to :**_= substitute( ${DS_SCANNER_INPUT}, /[^\d\w]*/, '' )_** solves the issue.

**Comment by johnposten** [comment]
New Intermec SDK is here - "\\barn\files\development\SDKs and Interpreters\Intermec SDKs\00003088_Intermec Scan Engine SDK (Version 1.6).msi"

Perhaps with that SDK we will no longer have to use the method that Ken Fletcher was using of listening for Windows events (this is what is in the dev branch that we were using).

**Comment by WebeWizard** [comment]
Fixed.
