### ISSUE TITLE
Support for Motorola LI4278 for use with Standalone client.

### ISSUE THREAD

**Issue by michaelnutt** [DataSplice/uniwedge-2000-windows#50]

**Comment by WebeWizard** [comment]
SDK from Zebra seems reasonable.  It would take me probably 2 work days to build and test.

**Comment by WebeWizard** [comment]
Peter ordered one, just waiting for it to arrive.  Should be able to start on it at the beginning of next week.

**Comment by WebeWizard** [comment]
This should be done now that we have the HID driver in the client.   Probably needs to see some use out in the wild to iron out remaining issues, but the initial development portion of this is complete.
